import Foundation

/// Aseprite JSON export format (generated by Aseprite's "Export Sprite Sheet" with JSON data).
public struct AsepriteData: Codable, Sendable {
    public let frames: [AsepriteFrame]
    public let meta: AsepriteMeta

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.meta = try container.decode(AsepriteMeta.self, forKey: .meta)

        // Aseprite can export frames as an array or a dictionary
        if let array = try? container.decode([AsepriteFrame].self, forKey: .frames) {
            self.frames = array
        } else if let dict = try? container.decode([String: AsepriteFrameData].self, forKey: .frames) {
            self.frames = dict.sorted(by: { $0.key < $1.key }).map { key, value in
                AsepriteFrame(filename: key, frame: value.frame, duration: value.duration,
                              rotated: value.rotated, trimmed: value.trimmed,
                              spriteSourceSize: value.spriteSourceSize, sourceSize: value.sourceSize)
            }
        } else {
            self.frames = []
        }
    }

    private enum CodingKeys: String, CodingKey {
        case frames, meta
    }
}

public struct AsepriteFrame: Codable, Sendable {
    public let filename: String?
    public let frame: AsepriteRect
    public let duration: Int // milliseconds
    public let rotated: Bool
    public let trimmed: Bool
    public let spriteSourceSize: AsepriteRect
    public let sourceSize: AsepriteSize
}

/// Internal: used when frames are exported as a dictionary.
struct AsepriteFrameData: Codable, Sendable {
    let frame: AsepriteRect
    let duration: Int
    let rotated: Bool
    let trimmed: Bool
    let spriteSourceSize: AsepriteRect
    let sourceSize: AsepriteSize
}

public struct AsepriteRect: Codable, Sendable {
    public let x: Int
    public let y: Int
    public let w: Int
    public let h: Int
}

public struct AsepriteSize: Codable, Sendable {
    public let w: Int
    public let h: Int
}

public struct AsepriteMeta: Codable, Sendable {
    public let app: String?
    public let version: String?
    public let image: String
    public let size: AsepriteSize
    public let scale: String?
    // swiftlint:disable:next discouraged_optional_collection
    public let frameTags: [AsepriteFrameTag]?
}

public struct AsepriteFrameTag: Codable, Sendable {
    public let name: String
    public let from: Int
    public let to: Int
    public let direction: String // "forward", "reverse", "pingpong"
}

/// Loads Aseprite JSON export files.
public struct AsepriteLoader: Sendable {
    public init() {}

    /// Parse an Aseprite JSON export from data.
    public func load(from data: Data) throws -> AsepriteData {
        let decoder = JSONDecoder()
        return try decoder.decode(AsepriteData.self, from: data)
    }

    /// Parse from raw bytes.
    public func load(from bytes: [UInt8]) throws -> AsepriteData {
        try load(from: Data(bytes))
    }
}
